# Site wide configuration

title:  Vishesh Duggar
url: 
website: https://vishesh.space
locale: en_US

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true


# Site owner
owner:
  name: Vishesh Duggar
  avatar: bio-photo.jpg
  bio: "5x founder. Co-founder & CTO Product @vamstar. 15+ years building and advising startups of all sizes. If you're building something cool, I'd love to hear about it."
  email: 
  disqus-shortname: visheshd
  twitter: vishaysh
  google:
    plus: #username
    analytics: UA-61117280-1 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: visheshd
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: visheshd
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
